mqtt:
  host: "localhost"
  port: 1883
  
client:
  id: "display"

topics:
  inference: "inference"
  stream: "streaming"
  publish_by: "adapter"

inference:
  label_path: "./configs/coco_labels.txt"
  width: 640
  height: 640

display:
  width: 640
  height: 640
  auto_resize: true
  show_fps: true
  show_inference_info: true
  show_local_time: true

record:
  enable: false
  filename: "display_vid"
